31/12/24 (18:55:45) | ERROR: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
03/01/25 (12:17:30) | ERROR: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
03/01/25 (12:21:11) | ERROR: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
03/01/25 (12:21:16) | ERROR: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
15/03/25 (18:13:09) | ERROR: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
Traceback (most recent call last):
  File "/usr/bin/bpytop", line 1357, in refresh
    for f in os.listdir(d):
             ~~~~~~~~~~^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/darth06/.config/bpytop/themes'
